### ISSUE TITLE
Add Crowdin Github Action

### ISSUE THREAD

**Issue by worldwidepixel** [notessentialsite/website#36]
The Crowdin Github action would allow us to automatically sync translations from our Crowdin, removing a lot of headache from the process of localisation.

**Comment by blryface** [comment]
im

**Comment by KTrain5169** [comment]
did not realise I was assigned sorry, kinda busy atm but I'll see to it asap

**Comment by worldwidepixel** [comment]
Almost a month of work finally culminating
