### ISSUE TITLE
Text that don't have entries in their respective lang JSONs don't show any text.

### ISSUE THREAD

**Issue by KTrain5169** [notessentialsite/website#46]
## Describe the bug here

(Issue raised by @Nitrrine)
My description skills are absolutely insane (at being terrible) so I'll just go with an example here.
Example: A new mod gets added to /alternatives
* The JSON for other languages are not updated with the new entry. No fields in there for that spot.
* As such, no text is displayed because, well, there's no text to display.

## Steps to reproduce

Step 1: Visit the /experiments page
Step 2: Select a language that doesn't have an entry for a specific mod (Snapper is the perfect test subject when this is written, as it only has an entry for en-US)
Step 3: Visit /alternatives
Step 4: Scroll until you see Snapper and note that it has no description.

## Expected result

Fallback text from the en-US JSON is displayed

### Additional info

Don't think any additional info is needed.

### Example images

![image](https://github.com/user-attachments/assets/a330b262-bef8-4332-aee3-f3dff6d3b75c)

## Checklist

- [x] I have clearly and, to the best of my ability, accurately stated info about the bug I'm experiencing.
- [x] I have searched for duplicate issues and have not found any.
- [ ] I did not read this section.

**Comment by worldwidepixel** [comment]
Sort of surprised that fallbacks didn't kick in. I wonder if the lack of the translation entry on all other languages caused this?

**Comment by KTrain5169** [comment]
Most likely. Usually the fallback text is an actual entry in the JSONs, but since new entries aren't immediately present in Crowdin there is no translation entry

**Comment by worldwidepixel** [comment]
~~We really need this crowdin connection~~

**Comment by blryface** [comment]
legit just gonna make an org called not essential and invite you guys

**Comment by KTrain5169** [comment]
> legit just gonna make an org called not essential and invite you guys

you are the owner of the crowdin = you still have to do it anyways

**Comment by KTrain5169** [comment]
Fixed? by letting the Action just paste the source strings into the entries if there is no translation.
